# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7c8c809e17c1469d129a389c8e37aee1ca42afd9c2b3ae04ce43a2f1e4336c8345d308782fd86761d990aba96a92c4392cb7283532cea834cca4695c6091c72

test:
  secret_key_base: ada1b7516f7f1e5fb51a04b66adac29fce0cbbfbabf3ded26b9b544b2b8acd8f01acb2f82f6e030b239e28055479268fb1cea261faf71cb37aef4c680f6069c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
